#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application as ConsoleApp;
use Instapp\Command;
use Instapp\Instapp;

$app = new Instapp();

$console = new ConsoleApp();
$console->add(new Command\FollowInLocationCommand($app));
$console->add(new Command\FollowInHashtagCommand($app));
$console->add(new Command\FollowUserFollowersCommand($app));
$console->add(new Command\LikeTimelineCommand($app));
$console->run();
